2019-04-16 10:20:43,577 ERROR: Exception on /index [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 32, in index
    language=language)
  File "<string>", line 4, in __init__
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 441, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 438, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 834, in _declarative_constructor
    "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
TypeError: 'language' is an invalid keyword argument for Post
2019-04-16 12:35:21,412 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-16 12:35:50,606 ERROR: Exception on /index [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 32, in index
    language=language)
  File "<string>", line 4, in __init__
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 441, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 438, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 834, in _declarative_constructor
    "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
TypeError: 'language' is an invalid keyword argument for Post
2019-04-16 12:44:24,933 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-16 12:44:29,846 ERROR: Exception on /index [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 31, in index
    post = Post(body=form.post.data, author=current_user, language=language)
  File "<string>", line 4, in __init__
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 441, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 438, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 834, in _declarative_constructor
    "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
TypeError: 'language' is an invalid keyword argument for Post
2019-04-16 12:44:36,835 ERROR: Exception on /index [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 31, in index
    post = Post(body=form.post.data, author=current_user, language=language)
  File "<string>", line 4, in __init__
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 441, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 438, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 834, in _declarative_constructor
    "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
TypeError: 'language' is an invalid keyword argument for Post
2019-04-16 12:45:35,935 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
